apiVersion: v1
kind: Secret

metadata:
  name: db-connection
type: Opaque

data:
  db_url: cG9zdGdyZXNxbDovL3Bvc3RncmVzLnRpbWRqYXFlZGV2cHZ6aXF5YXRtOmtBeTJVTG9kSFpCU050YmJAYXdzLTAtdXMtZWFzdC0xLnBvb2xlci5zdXBhYmFzZS5jb206NjU0My9wb3N0Z3Jlcw==
