apiVersion: v1
kind: Service

metadata:
  name: planner-service
  labels:
    app: planner

spec:
  selector:
    app: planner
  type: ClusterIP
  ports:
    - name: planner-service
      port: 80
      targetPort: 3333
      protocol: TCP
